nameOverride: ""
fullnameOverride: ""

customerUi:
  replicaCount: 1

  image:
    repository: customer-ui
    tag: demo
    pullPolicy: Never

  service:
    type: NodePort
    port: 80
    nodePort: 30080


orchestrator:
  replicaCount: 1

  image:
    repository: orchestrator-svc
    tag: demo
    pullPolicy: Never

  service:
    type: NodePort
    port: 8001
    nodePort: 30081

  env:
    appEnv: production
    host: 0.0.0.0
    port: "8001"

mcpServer:
  replicaCount: 1

  image:
    repository: mcp-server
    tag: demo
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 8000