nameOverride: ""
fullnameOverride: ""

customerUi:
  replicaCount: 1

  image:
    repository: customer-ui
    tag: demo
    pullPolicy: Never

  service:
    type: NodePort
    port: 80
    nodePort: 30080