"""Private LangGraph state for the read-only DB sub-agent.

The parent orchestrator invokes the DB agent with the active step and the
request-scoped ``RequestContext``. This module converts that boundary input
into a fully initialized state used only inside the DB-agent subgraph.

The state preserves the exact ``RequestContext`` object so ``run_id``,
``request_id``, ``session_id``, and ``tenant_id`` remain consistent across:

- LLM telemetry events.
- MCP tool calls.
- Retry events.
- The final DB-agent result.

This module contains no routing, SQL generation, validation, logging, retry,
or tool-calling logic. It defines state structure and initialization only.
"""

from __future__ import annotations

import time
from typing import Any, Literal, TypedDict

from app.context import RequestContext

from .models import (
    DBAgentResult,
    DBOperation,
    DocumentSearchResult,
    QueryResult,
    SQLPlan,
    SchemaResult,
)


class DBAgentState(TypedDict):
    """State carried through one invocation of the DB-agent subgraph.

    Parent boundary fields
    ----------------------
    ctx:
        Request context created by middleware. It contains the four required
        correlation IDs and must never be replaced inside the DB agent.
    step_key:
        Parent step identifier used to store the final result in
        ``RunState["step_results"]``.
    step_sequence:
        One-based position of the current step in the parent execution plan.
    instruction:
        DB-specific instruction produced by the deterministic parent router.
    prior_step_outputs:
        Results from steps completed earlier in the same request.
    config:
        Request-level configuration inherited from the parent ``RunState``.

    Internal execution fields
    -------------------------
    operation:
        Selected DB-agent path: SQL fetch or document search.
    schema:
        Validated schema returned by the MCP ``get_schema`` tool, or an
        optional schema hint supplied by the parent adapter.
    sql_plan:
        Structured SQL plan generated by the shared LLM through the DB-specific
        LLM adapter.
    validation_errors:
        Sanitized validation failures produced by pure Python validation.
    query_result:
        Validated result returned by the MCP ``run_query`` tool.
    document_result:
        Validated result returned by the MCP ``search_documents`` tool.
    call_sequence:
        Monotonically increasing logical sequence shared by LLM and MCP calls.
        Transport retries retain the same call sequence.
    correction_count:
        Number of SQL self-correction passes already performed. The graph will
        permit at most one correction.
    last_error:
        Sanitized intermediate error available to routing or SQL correction.
    result:
        Stable terminal result returned to the parent orchestrator.
    status:
        Current internal lifecycle status.
    error:
        Sanitized terminal error category returned on failure.
    started_at:
        Monotonic timestamp used to calculate total agent duration.
    """

    # Input copied from the parent orchestrator.
    ctx: RequestContext
    step_key: str
    step_sequence: int
    instruction: str
    prior_step_outputs: dict[str, dict[str, Any]]
    config: dict[str, Any]

    # Internal routing and execution state.
    operation: DBOperation | None
    schema: SchemaResult | None
    sql_plan: SQLPlan | None
    validation_errors: list[str]

    query_result: QueryResult | None
    document_result: DocumentSearchResult | None

    call_sequence: int
    correction_count: int
    last_error: str | None

    result: DBAgentResult | None
    status: Literal["running", "success", "error"]
    error: str | None
    started_at: float


def create_db_agent_state(
    *,
    ctx: RequestContext,
    step_key: str,
    step_sequence: int,
    instruction: str,
    prior_step_outputs: dict[str, dict[str, Any]] | None = None,
    config: dict[str, Any] | None = None,
    schema_hint: SchemaResult | None = None,
    started_at: float | None = None,
) -> DBAgentState:
    """Create an initialized state for one DB-agent invocation.

    Parameters
    ----------
    ctx:
        Existing request context supplied by the parent orchestrator. The same
        object is retained so correlation IDs cannot drift.
    step_key:
        Unique key of the active parent step.
    step_sequence:
        One-based position of the active step in the parent plan.
    instruction:
        DB-specific instruction the sub-agent must execute.
    prior_step_outputs:
        Optional outputs from earlier steps in the same request. The top-level
        dictionary is shallow-copied to avoid replacing entries in the parent
        orchestrator's dictionary.
    config:
        Optional request-level configuration. The dictionary is shallow-copied
        to isolate the private subgraph from parent-state mutation.
    schema_hint:
        Optional validated schema supplied by a future request-level schema
        cache. The current repository may leave this as ``None``.
    started_at:
        Optional monotonic timestamp override used by deterministic unit tests.

    Returns
    -------
    DBAgentState
        A complete state ready for ``compiled_db_agent.ainvoke``.

    Raises
    ------
    ValueError
        If the step key, step sequence, instruction, or supplied timestamp is
        invalid.
    """

    normalized_step_key = step_key.strip()
    normalized_instruction = instruction.strip()

    if not normalized_step_key:
        raise ValueError("step_key must not be empty")

    if step_sequence < 1:
        raise ValueError("step_sequence must be greater than zero")

    if not normalized_instruction:
        raise ValueError("instruction must not be empty")

    if started_at is not None and started_at < 0:
        raise ValueError("started_at must not be negative")

    return DBAgentState(
        ctx=ctx,
        step_key=normalized_step_key,
        step_sequence=step_sequence,
        instruction=normalized_instruction,
        prior_step_outputs=dict(prior_step_outputs or {}),
        config=dict(config or {}),
        operation=None,
        schema=schema_hint,
        sql_plan=None,
        validation_errors=[],
        query_result=None,
        document_result=None,
        call_sequence=0,
        correction_count=0,
        last_error=None,
        result=None,
        status="running",
        error=None,
        started_at=(
            time.perf_counter()
            if started_at is None
            else started_at
        ),
    )
