"""Deterministic validation for DB-agent SQL and MCP tool responses.

This module provides two layers of validation:

1. Conservative SQL validation before a generated query reaches ``run_query``.
2. Strict parsing of responses returned by the DB-facing MCP tools.

The SQL checks are intentionally conservative and support read-only ``SELECT``
and ``WITH ... SELECT`` statements. They are a defense-in-depth guardrail, not
a replacement for the MCP server's read-only database role and transaction.

No LangGraph routing, MCP calls, retries, LLM calls, or logging belong here.
Validation errors use stable categories so callers can report failures without
logging raw SQL rows, document text, or complete tool responses.
"""

from __future__ import annotations

import re
from typing import TypeVar

from pydantic import BaseModel, ValidationError

from .models import (
    DocumentSearchResult,
    QueryResult,
    SchemaResult,
)

MAX_SQL_LENGTH = 10_000

_FORBIDDEN_KEYWORDS = (
    "INSERT",
    "UPDATE",
    "DELETE",
    "MERGE",
    "UPSERT",
    "CREATE",
    "ALTER",
    "DROP",
    "TRUNCATE",
    "GRANT",
    "REVOKE",
    "COPY",
    "CALL",
    "DO",
    "EXECUTE",
    "VACUUM",
    "ANALYZE",
    "REFRESH",
    "REINDEX",
    "CLUSTER",
    "COMMENT",
    "INTO",
)

_LOCKING_CLAUSE_PATTERN = re.compile(
    r"\bFOR\s+(?:NO\s+KEY\s+UPDATE|KEY\s+SHARE|UPDATE|SHARE)\b",
    flags=re.IGNORECASE,
)

ModelT = TypeVar("ModelT", bound=BaseModel)


class DBToolResultValidationError(ValueError):
    """Raised when an MCP tool response violates the expected DB contract.

    The exception string contains only a stable error category. The original
    Pydantic validation error remains available through exception chaining for
    tests and local debugging, but callers should not emit it to telemetry.
    """

    def __init__(self, category: str) -> None:
        """Create a sanitized tool-result validation error."""

        self.category = category
        super().__init__(category)


def normalize_sql(sql: str) -> str:
    """Normalize harmless outer whitespace and one trailing semicolon.

    Parameters
    ----------
    sql:
        Candidate SQL generated by the DB LLM adapter.

    Returns
    -------
    str
        SQL with surrounding whitespace removed and at most one trailing
        semicolon removed.

    Notes
    -----
    This function does not make SQL safe. Call ``validate_select_sql`` before
    sending the normalized value to the MCP ``run_query`` tool.
    """

    normalized = sql.strip()

    if normalized.endswith(";"):
        normalized = normalized[:-1].rstrip()

    return normalized


def validate_select_sql(sql: str) -> list[str]:
    """Return stable validation errors for a candidate read-only SQL query.

    Accepted queries must:

    - Be non-empty.
    - Stay within ``MAX_SQL_LENGTH``.
    - Contain no null byte.
    - Contain no SQL comments.
    - Contain only one statement.
    - Begin with ``SELECT`` or ``WITH``.
    - Contain no write, DDL, administrative, or locking operation.
    - Contain a ``SELECT`` token when beginning with ``WITH``.

    The validator masks quoted string and identifier content before checking
    semicolons and keywords. This prevents values such as ``'update pending'``
    from being mistaken for SQL operations.

    Parameters
    ----------
    sql:
        Candidate SQL generated by the DB LLM adapter.

    Returns
    -------
    list[str]
        Stable validation categories. An empty list means the query passed the
        local guardrail.
    """

    errors: list[str] = []

    if not isinstance(sql, str):
        return ["invalid_sql_type"]

    normalized = normalize_sql(sql)

    if not normalized:
        return ["empty_sql"]

    if len(normalized) > MAX_SQL_LENGTH:
        errors.append("sql_too_long")

    if "\x00" in normalized:
        errors.append("null_byte_not_allowed")

    masked_sql, quote_is_closed = _mask_quoted_content(normalized)

    if not quote_is_closed:
        errors.append("unterminated_quote")

    if "--" in masked_sql or "/*" in masked_sql or "*/" in masked_sql:
        errors.append("comments_not_allowed")

    if ";" in masked_sql:
        errors.append("multiple_statements")

    first_keyword_match = re.match(
        r"^\s*(SELECT|WITH)\b",
        masked_sql,
        flags=re.IGNORECASE,
    )

    if first_keyword_match is None:
        errors.append("select_only")
    elif first_keyword_match.group(1).upper() == "WITH":
        if re.search(r"\bSELECT\b", masked_sql, flags=re.IGNORECASE) is None:
            errors.append("with_query_requires_select")

    for keyword in _FORBIDDEN_KEYWORDS:
        if re.search(
            rf"\b{re.escape(keyword)}\b",
            masked_sql,
            flags=re.IGNORECASE,
        ):
            errors.append(f"forbidden_keyword:{keyword.lower()}")

    if _LOCKING_CLAUSE_PATTERN.search(masked_sql):
        errors.append("locking_clause_not_allowed")

    return _deduplicate(errors)


def validate_schema_result(value: object) -> SchemaResult:
    """Parse and validate a response from the MCP ``get_schema`` tool.

    Parameters
    ----------
    value:
        Raw value returned through the shared MCP client.

    Returns
    -------
    SchemaResult
        Strictly validated schema metadata.

    Raises
    ------
    DBToolResultValidationError
        If the response does not match the published schema-tool contract.
    """

    return _validate_tool_result(
        model_type=SchemaResult,
        value=value,
        category="invalid_schema_result",
    )


def validate_query_result(value: object) -> QueryResult:
    """Parse and validate a response from the MCP ``run_query`` tool.

    Parameters
    ----------
    value:
        Raw value returned through the shared MCP client.

    Returns
    -------
    QueryResult
        Strictly validated rows, row count, and execution duration.

    Raises
    ------
    DBToolResultValidationError
        If the response does not match the published query-tool contract.
    """

    return _validate_tool_result(
        model_type=QueryResult,
        value=value,
        category="invalid_query_result",
    )


def validate_document_result(value: object) -> DocumentSearchResult:
    """Parse and validate a response from ``search_documents``.

    Parameters
    ----------
    value:
        Raw value returned through the shared MCP client.

    Returns
    -------
    DocumentSearchResult
        Strictly validated document chunks and retrieval identifiers.

    Raises
    ------
    DBToolResultValidationError
        If the response does not match the published document-search contract.
    """

    return _validate_tool_result(
        model_type=DocumentSearchResult,
        value=value,
        category="invalid_document_result",
    )


def _validate_tool_result(
    *,
    model_type: type[ModelT],
    value: object,
    category: str,
) -> ModelT:
    """Validate an MCP response while exposing only a safe error category."""

    try:
        return model_type.model_validate(value)
    except (ValidationError, TypeError, ValueError) as exc:
        raise DBToolResultValidationError(category) from exc


def _mask_quoted_content(sql: str) -> tuple[str, bool]:
    """Replace quoted content with spaces while preserving SQL structure.

    Both PostgreSQL single-quoted strings and double-quoted identifiers are
    handled. Doubled quote characters inside a quoted value are treated as
    escapes.

    Returns
    -------
    tuple[str, bool]
        Masked SQL and whether every opened quote was closed.
    """

    output: list[str] = []
    active_quote: str | None = None
    index = 0

    while index < len(sql):
        character = sql[index]

        if active_quote is None:
            if character in {"'", '"'}:
                active_quote = character
                output.append(" ")
            else:
                output.append(character)

            index += 1
            continue

        if character == active_quote:
            next_index = index + 1

            if next_index < len(sql) and sql[next_index] == active_quote:
                output.extend((" ", " "))
                index += 2
                continue

            active_quote = None
            output.append(" ")
            index += 1
            continue

        output.append(" ")
        index += 1

    return "".join(output), active_quote is None


def _deduplicate(values: list[str]) -> list[str]:
    """Return values in their original order without duplicates."""

    return list(dict.fromkeys(values))
