apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-chat.fullname" . }}-customer-ui
  labels:
    app.kubernetes.io/name: customer-ui
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  replicas: {{ .Values.customerUi.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/name: customer-ui
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-ui
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: customer-ui
          image: "{{ .Values.customerUi.image.repository }}:{{ .Values.customerUi.image.tag }}"
          imagePullPolicy: {{ .Values.customerUi.image.pullPolicy }}
          env:
            - name: ORCHESTRATOR_CHAT_URL
              value: {{ printf "http://%s-orchestrator:%v/chat" (include "ai-chat.fullname" .) .Values.orchestrator.service.port | quote }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
