apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-chat.fullname" . }}-otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.otelCollector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args: ["--config=/etc/otelcol-contrib/collector-config.yaml"]
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.otelCollector.service.grpcPort }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ .Values.otelCollector.service.httpPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib/collector-config.yaml
              subPath: collector-config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "ai-chat.fullname" . }}-otel-collector
